import { hexToOklch } from "./color-space";
import { formatOklch } from "./format";
import type { NamedScale } from "./palettes";
import { SHADCN_COLOR_TOKENS, shadcnTokens, type SemanticTokens } from "./semantic";

const GENERATED = "Generated by Tintwork (Groundwork Technologies)";

const words = (name: string) => name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
export const camel = (name: string) => words(name).map((w, i) => (i === 0 ? w.toLowerCase() : w[0]!.toUpperCase() + w.slice(1).toLowerCase())).join("");
export const pascal = (name: string) => words(name).map((w) => w[0]!.toUpperCase() + w.slice(1).toLowerCase()).join("");
export const snake = (name: string) => words(name).map((w) => w.toLowerCase()).join("_");
const upper = (hex: string) => hex.slice(1).toUpperCase();

function semantic(full: NamedScale[]): { light: SemanticTokens; dark: SemanticTokens } | null {
  try {
    return { light: shadcnTokens(full, "light"), dark: shadcnTokens(full, "dark") };
  } catch {
    return null;
  }
}

/** Map semantic tokens onto platform color-scheme roles. */
const ROLES: [role: string, token: string][] = [
  ["primary", "primary"],
  ["onPrimary", "primary-foreground"],
  ["secondary", "secondary"],
  ["onSecondary", "secondary-foreground"],
  ["error", "destructive"],
  ["onError", "destructive-foreground"],
  ["background", "background"],
  ["onBackground", "foreground"],
  ["surface", "card"],
  ["onSurface", "card-foreground"],
  ["outline", "border"],
];

// ---- Style Dictionary -------------------------------------------------------

export function styleDictionaryTokens(scales: NamedScale[]): string {
  const color = Object.fromEntries(
    scales.map((s) => [s.name, Object.fromEntries(s.steps.map((x) => [String(x.stop), { $value: x.hex, $type: "color" }]))]),
  );
  return JSON.stringify({ $description: GENERATED, color }, null, 2) + "\n";
}

export function styleDictionaryConfig(): string {
  return (
    JSON.stringify(
      {
        source: ["tokens/**/*.json"],
        platforms: {
          css: { transformGroup: "css", buildPath: "build/css/", files: [{ destination: "variables.css", format: "css/variables" }] },
          scss: { transformGroup: "scss", buildPath: "build/scss/", files: [{ destination: "_variables.scss", format: "scss/variables" }] },
          js: { transformGroup: "js", buildPath: "build/js/", files: [{ destination: "colors.js", format: "javascript/es6" }] },
        },
      },
      null,
      2,
    ) + "\n"
  );
}

// ---- Flutter ------------------------------------------------------------------

const dartColor = (hex: string) => `Color(0xFF${upper(hex)})`;

export function flutterDart(scales: NamedScale[], full: NamedScale[]): string {
  const swatches = scales
    .map((s) => {
      const primary = s.steps.find((x) => x.stop === 500)!.hex;
      const rows = s.steps.map((x) => `    ${x.stop}: ${dartColor(x.hex)},`).join("\n");
      return `  static const MaterialColor ${camel(s.name)} = MaterialColor(0xFF${upper(primary)}, <int, Color>{\n${rows}\n  });`;
    })
    .join("\n\n");
  const sem = semantic(full);
  const scheme = (t: SemanticTokens, brightness: string) => {
    // Flutter's ColorScheme no longer needs background/onBackground; surface covers them.
    const lines = ROLES.filter(([role]) => role !== "background" && role !== "onBackground").map(([role, token]) => `    ${role}: ${dartColor(t[token]!)},`);
    return `  static const ColorScheme ${brightness} = ColorScheme(\n    brightness: Brightness.${brightness},\n${lines.join("\n")}\n  );`;
  };
  const schemes = sem ? `\n\n/// Material 3 color schemes built from the same palette (every text/background pair is AA).\nabstract final class TintworkSchemes {\n${scheme(sem.light, "light")}\n\n${scheme(sem.dark, "dark")}\n}` : "";
  return `// ${GENERATED}. Requires Dart 3 and Flutter 3.x.\nimport 'package:flutter/material.dart';\n\nabstract final class TintworkColors {\n${swatches}\n}${schemes}\n`;
}

// ---- Android ------------------------------------------------------------------

export function androidColorsXml(scales: NamedScale[], full: NamedScale[]): string {
  const rows = scales.flatMap((s) => s.steps.map((x) => `    <color name="${snake(s.name)}_${x.stop}">#${upper(x.hex)}</color>`));
  const sem = semantic(full);
  const semRows = sem ? ["", "    <!-- Semantic, light. Dark overrides live in values-night/colors.xml -->", ...SHADCN_COLOR_TOKENS.filter((k) => !k.startsWith("chart")).map((k) => `    <color name="tw_${snake(k)}">#${upper(sem.light[k]!)}</color>`)] : [];
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${GENERATED} -->\n<resources>\n${[...rows, ...semRows].join("\n")}\n</resources>\n`;
}

export function androidNightXml(full: NamedScale[]): string | null {
  const sem = semantic(full);
  if (!sem) return null;
  const rows = SHADCN_COLOR_TOKENS.filter((k) => !k.startsWith("chart")).map((k) => `    <color name="tw_${snake(k)}">#${upper(sem.dark[k]!)}</color>`);
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${GENERATED}: dark theme -->\n<resources>\n${rows.join("\n")}\n</resources>\n`;
}

// ---- Jetpack Compose ------------------------------------------------------------

export function composeKotlin(scales: NamedScale[], full: NamedScale[]): string {
  const vals = scales.flatMap((s) => s.steps.map((x) => `val ${pascal(s.name)}${x.stop} = Color(0xFF${upper(x.hex)})`));
  const sem = semantic(full);
  const roleMap = (t: SemanticTokens) => ROLES.map(([role, token]) => `    ${role} = Color(0xFF${upper(t[token]!)}),`).join("\n");
  const schemes = sem ? `\n\nval TintworkLightColors = lightColorScheme(\n${roleMap(sem.light)}\n)\n\nval TintworkDarkColors = darkColorScheme(\n${roleMap(sem.dark)}\n)` : "";
  return `// ${GENERATED}\npackage com.example.ui.theme\n\nimport androidx.compose.material3.darkColorScheme\nimport androidx.compose.material3.lightColorScheme\nimport androidx.compose.ui.graphics.Color\n\n${vals.join("\n")}${schemes}\n`;
}

// ---- iOS ------------------------------------------------------------------------

export function swiftColors(scales: NamedScale[], full: NamedScale[]): string {
  const vals = scales.flatMap((s) => s.steps.map((x) => `    static let ${camel(s.name)}${x.stop} = Color(hex: 0x${upper(x.hex)})`));
  const sem = semantic(full);
  const semRows = sem ? ["", "    // Semantic colors with light and dark variants live in the asset catalog (Tintwork.xcassets)."].concat(SHADCN_COLOR_TOKENS.filter((k) => !k.startsWith("chart")).map((k) => `    static let tw${pascal(k)} = Color("Tw${pascal(k)}")`)) : [];
  return `// ${GENERATED}\nimport SwiftUI\n\nextension Color {\n    fileprivate init(hex: UInt32) {\n        self.init(\n            .sRGB,\n            red: Double((hex >> 16) & 0xFF) / 255,\n            green: Double((hex >> 8) & 0xFF) / 255,\n            blue: Double(hex & 0xFF) / 255,\n            opacity: 1\n        )\n    }\n\n${vals.join("\n")}${semRows.length ? "\n" + semRows.join("\n") : ""}\n}\n`;
}

const comp = (hex: string, i: number) => (parseInt(hex.slice(1 + i * 2, 3 + i * 2), 16) / 255).toFixed(3);
const colorEntry = (hex: string, appearance?: "dark") =>
  ({
    ...(appearance ? { appearances: [{ appearance: "luminosity", value: "dark" }] } : {}),
    color: { "color-space": "srgb", components: { alpha: "1.000", blue: comp(hex, 2), green: comp(hex, 1), red: comp(hex, 0) } },
    idiom: "universal",
  }) as const;

/** Files for an Xcode asset catalog: one colorset per shade and per semantic role. */
export function xcassetsFiles(scales: NamedScale[], full: NamedScale[]): { path: string; content: string }[] {
  const info = { author: "xcode", version: 1 };
  const root = "ios/Tintwork.xcassets";
  const files = [{ path: `${root}/Contents.json`, content: JSON.stringify({ info }, null, 2) + "\n" }];
  for (const s of scales)
    for (const x of s.steps) files.push({ path: `${root}/${pascal(s.name)}${x.stop}.colorset/Contents.json`, content: JSON.stringify({ colors: [colorEntry(x.hex)], info }, null, 2) + "\n" });
  const sem = semantic(full);
  if (sem)
    for (const k of SHADCN_COLOR_TOKENS.filter((t) => !t.startsWith("chart")))
      files.push({ path: `${root}/Tw${pascal(k)}.colorset/Contents.json`, content: JSON.stringify({ colors: [colorEntry(sem.light[k]!), colorEntry(sem.dark[k]!, "dark")], info }, null, 2) + "\n" });
  return files;
}

// ---- Modern CSS -----------------------------------------------------------------

export function modernCss(scales: NamedScale[], full: NamedScale[], sourceUrl?: string): string {
  const hexRows = scales.flatMap((s) => s.steps.map((x) => `  --${s.name}-${x.stop}: ${x.hex};`));
  const okRows = scales.flatMap((s) => s.steps.map((x) => `    --${s.name}-${x.stop}: ${formatOklch(hexToOklch(x.hex) ?? x.oklch)};`));
  const sem = semantic(full);
  const semRows = sem ? SHADCN_COLOR_TOKENS.filter((k) => !k.startsWith("chart")).map((k) => `  --${k}: light-dark(${sem.light[k]}, ${sem.dark[k]});`) : [];
  return (
    `/* ${GENERATED}${sourceUrl ? ` — ${sourceUrl}` : ""} */\n` +
    `/* Palette: hex everywhere, OKLCH where supported. */\n:root {\n${hexRows.join("\n")}\n}\n\n@supports (color: oklch(0% 0 0)) {\n  :root {\n${okRows.join("\n")}\n  }\n}\n` +
    (semRows.length ? `\n/* Semantic tokens: one declaration serves light and dark (light-dark() needs color-scheme). */\n:root {\n  color-scheme: light dark;\n${semRows.join("\n")}\n}\n` : "")
  );
}
