import { formatHsl, formatOklch, formatP3, formatRgb, type ColorSyntax } from "./format";
import type { NamedScale } from "./palettes";
import type { ScaleStep } from "./scale";

export type ExportFormat = "tailwind-v4" | "tailwind-v3" | "css" | "scss" | "json" | "dtcg" | "tokens-studio";
export type V3Module = "cjs" | "esm" | "ts";

export interface ExportOptions {
  format: ExportFormat;
  syntax: ColorSyntax;
  /** Tailwind v3 file flavour. */
  v3Module?: V3Module;
  /** Tailwind v4: also drop the default palette with `--color-*: initial`. */
  resetDefaults?: boolean;
  /** Share link written into a header comment so the palette can be reopened. */
  sourceUrl?: string;
}

export const FORMAT_LABELS: Record<ExportFormat, string> = {
  "tailwind-v4": "Tailwind v4 (@theme)",
  "tailwind-v3": "Tailwind v3 (config)",
  css: "CSS variables",
  scss: "SCSS",
  json: "JSON",
  dtcg: "Design tokens (DTCG)",
  "tokens-studio": "Tokens Studio / Figma",
};

export const FORMAT_FILES: Record<ExportFormat, string> = {
  "tailwind-v4": "tintwork-theme.css",
  "tailwind-v3": "tailwind.colors.js",
  css: "tintwork-colors.css",
  scss: "_tintwork-colors.scss",
  json: "tintwork-colors.json",
  dtcg: "tintwork-tokens.json",
  "tokens-studio": "tintwork-tokens-studio.json",
};

export function colorString(step: ScaleStep, syntax: ColorSyntax): string {
  switch (syntax) {
    case "hex":
      return step.hex;
    case "hsl":
      return formatHsl(step.hex);
    case "rgb":
      return formatRgb(step.hex);
    case "p3":
      return formatP3(step.oklch);
    case "oklch":
      return formatOklch(step.oklch);
  }
}

const lineHeader = (url: string | undefined, prefix: string) =>
  `${prefix} Generated by Tintwork (Groundwork Technologies)\n${url ? `${prefix} ${url}\n` : ""}`;
const blockHeader = (url?: string) => `/* Generated by Tintwork (Groundwork Technologies)${url ? ` — ${url}` : ""} */\n`;

const q = (s: string) => `'${s}'`;

function tailwindV4(scales: NamedScale[], o: ExportOptions): string {
  const lines = scales.flatMap((s) => [
    ...s.steps.map((x) => `  --color-${s.name}-${x.stop}: ${colorString(x, o.syntax)};`),
    "",
  ]);
  if (o.resetDefaults) lines.unshift("  --color-*: initial;", "");
  lines.pop();
  return `${blockHeader(o.sourceUrl)}@import "tailwindcss";\n\n@theme {\n${lines.join("\n")}\n}\n`;
}

function tailwindV3(scales: NamedScale[], o: ExportOptions): string {
  const body = scales
    .map((s) => `        ${/^[a-z]+$/.test(s.name) ? s.name : q(s.name)}: {\n${s.steps.map((x) => `          ${x.stop}: ${q(colorString(x, o.syntax))},`).join("\n")}\n        },`)
    .join("\n");
  const cfg = `{\n  theme: {\n    extend: {\n      colors: {\n${body.replace(/^ {2}/gm, "")}\n      },\n    },\n  },\n}`;
  const h = lineHeader(o.sourceUrl, "//");
  switch (o.v3Module ?? "esm") {
    case "cjs":
      return `${h}/** @type {import('tailwindcss').Config} */\nmodule.exports = ${cfg};\n`;
    case "ts":
      return `${h}import type { Config } from 'tailwindcss';\n\nexport default ${cfg} satisfies Config;\n`;
    default:
      return `${h}/** @type {import('tailwindcss').Config} */\nexport default ${cfg};\n`;
  }
}

function cssVars(scales: NamedScale[], o: ExportOptions): string {
  const lines = scales.flatMap((s) => s.steps.map((x) => `  --${s.name}-${x.stop}: ${colorString(x, o.syntax)};`));
  return `${blockHeader(o.sourceUrl)}:root {\n${lines.join("\n")}\n}\n`;
}

function scss(scales: NamedScale[], o: ExportOptions): string {
  const vars = scales.map((s) => s.steps.map((x) => `$${s.name}-${x.stop}: ${colorString(x, o.syntax)};`).join("\n")).join("\n\n");
  const maps = scales
    .map((s) => `$${s.name}: (\n${s.steps.map((x) => `  ${x.stop}: $${s.name}-${x.stop},`).join("\n")}\n);`)
    .join("\n\n");
  return `${lineHeader(o.sourceUrl, "//")}\n${vars}\n\n${maps}\n`;
}

function tree<T>(scales: NamedScale[], leaf: (x: ScaleStep) => T): Record<string, Record<string, T>> {
  return Object.fromEntries(scales.map((s) => [s.name, Object.fromEntries(s.steps.map((x) => [String(x.stop), leaf(x)]))]));
}

function json(scales: NamedScale[], o: ExportOptions): string {
  return JSON.stringify(tree(scales, (x) => colorString(x, o.syntax)), null, 2) + "\n";
}

const round = (n: number, dp: number) => Number(n.toFixed(dp));

function dtcg(scales: NamedScale[]): string {
  const t = tree(scales, (x) => ({
    $type: "color",
    $value: { colorSpace: "oklch", components: [round(x.oklch.l, 4), round(x.oklch.c, 4), round(x.oklch.h, 2)], hex: x.hex },
  }));
  return JSON.stringify({ $description: "Generated by Tintwork (Groundwork Technologies)", ...t }, null, 2) + "\n";
}

function tokensStudio(scales: NamedScale[], o: ExportOptions): string {
  const t = tree(scales, (x) => ({ value: colorString(x, o.syntax === "oklch" || o.syntax === "p3" ? "hex" : o.syntax), type: "color" }));
  return JSON.stringify(t, null, 2) + "\n";
}

/** Render scales in the requested format. Deterministic. */
export function exportScales(scales: NamedScale[], o: ExportOptions): string {
  switch (o.format) {
    case "tailwind-v4":
      return tailwindV4(scales, o);
    case "tailwind-v3":
      return tailwindV3(scales, o);
    case "css":
      return cssVars(scales, o);
    case "scss":
      return scss(scales, o);
    case "json":
      return json(scales, o);
    case "dtcg":
      return dtcg(scales);
    case "tokens-studio":
      return tokensStudio(scales, o);
  }
}
