import { hexToOklch } from "./color-space";
import { formatHsl, formatOklch, formatP3, formatRgb, type ColorSyntax } from "./format";
import {
  androidColorsXml,
  androidNightXml,
  composeKotlin,
  flutterDart,
  modernCss,
  styleDictionaryConfig,
  styleDictionaryTokens,
  swiftColors,
  xcassetsFiles,
} from "./export-platforms";
import { SHADCN_COLOR_TOKENS, shadcnTokens } from "./semantic";
import { createZip, type ZipFile } from "./zip";
import type { NamedScale } from "./palettes";
import type { ScaleStep } from "./scale";

export type ExportFormat = "tailwind-v4" | "tailwind-v3" | "css" | "scss" | "json" | "dtcg" | "tokens-studio" | "shadcn" | "style-dictionary" | "css-modern" | "flutter" | "android" | "compose" | "ios";
export type V3Module = "cjs" | "esm" | "ts";

export interface ExportOptions {
  format: ExportFormat;
  syntax: ColorSyntax;
  /** Tailwind v3 file flavour. */
  v3Module?: V3Module;
  /** Tailwind v4: also drop the default palette with `--color-*: initial`. */
  resetDefaults?: boolean;
  /** Share link written into a header comment so the palette can be reopened. */
  sourceUrl?: string;
  /**
   * The complete set (brand, neutral, status) used for semantic tokens in the shadcn, Flutter,
   * Android, Compose and iOS exports. Defaults to the scales being exported.
   */
  full?: NamedScale[];
}

export const FORMAT_LABELS: Record<ExportFormat, string> = {
  "tailwind-v4": "Tailwind v4 (@theme)",
  "tailwind-v3": "Tailwind v3 (config)",
  css: "CSS variables",
  scss: "SCSS",
  json: "JSON",
  dtcg: "Design tokens (DTCG)",
  "tokens-studio": "Tokens Studio / Figma",
  shadcn: "shadcn/ui theme",
  "css-modern": "Modern CSS (light-dark)",
  "style-dictionary": "Style Dictionary",
  flutter: "Flutter (Dart)",
  android: "Android (colors.xml)",
  compose: "Jetpack Compose",
  ios: "iOS (SwiftUI)",
};

export const FORMAT_FILES: Record<ExportFormat, string> = {
  "tailwind-v4": "tintwork-theme.css",
  "tailwind-v3": "tailwind.colors.js",
  css: "tintwork-colors.css",
  scss: "_tintwork-colors.scss",
  json: "tintwork-colors.json",
  dtcg: "tintwork-tokens.json",
  "tokens-studio": "tintwork-tokens-studio.json",
  shadcn: "tintwork-shadcn-theme.css",
  "css-modern": "tintwork-modern.css",
  "style-dictionary": "tintwork-style-dictionary.json",
  flutter: "tintwork_colors.dart",
  android: "colors.xml",
  compose: "Color.kt",
  ios: "TintworkColors.swift",
};

export function colorString(step: ScaleStep, syntax: ColorSyntax): string {
  switch (syntax) {
    case "hex":
      return step.hex;
    case "hsl":
      return formatHsl(step.hex);
    case "rgb":
      return formatRgb(step.hex);
    case "p3":
      return formatP3(step.oklch);
    case "oklch":
      return formatOklch(step.oklch);
  }
}

const lineHeader = (url: string | undefined, prefix: string) =>
  `${prefix} Generated by Tintwork (Groundwork Technologies)\n${url ? `${prefix} ${url}\n` : ""}`;
const blockHeader = (url?: string) => `/* Generated by Tintwork (Groundwork Technologies)${url ? ` — ${url}` : ""} */\n`;

const q = (s: string) => `'${s}'`;

function tailwindV4(scales: NamedScale[], o: ExportOptions): string {
  const lines = scales.flatMap((s) => [
    ...s.steps.map((x) => `  --color-${s.name}-${x.stop}: ${colorString(x, o.syntax)};`),
    "",
  ]);
  if (o.resetDefaults) lines.unshift("  --color-*: initial;", "");
  lines.pop();
  return `${blockHeader(o.sourceUrl)}@import "tailwindcss";\n\n@theme {\n${lines.join("\n")}\n}\n`;
}

function tailwindV3(scales: NamedScale[], o: ExportOptions): string {
  const body = scales
    .map((s) => `        ${/^[a-z]+$/.test(s.name) ? s.name : q(s.name)}: {\n${s.steps.map((x) => `          ${x.stop}: ${q(colorString(x, o.syntax))},`).join("\n")}\n        },`)
    .join("\n");
  const cfg = `{\n  theme: {\n    extend: {\n      colors: {\n${body.replace(/^ {2}/gm, "")}\n      },\n    },\n  },\n}`;
  const h = lineHeader(o.sourceUrl, "//");
  switch (o.v3Module ?? "esm") {
    case "cjs":
      return `${h}/** @type {import('tailwindcss').Config} */\nmodule.exports = ${cfg};\n`;
    case "ts":
      return `${h}import type { Config } from 'tailwindcss';\n\nexport default ${cfg} satisfies Config;\n`;
    default:
      return `${h}/** @type {import('tailwindcss').Config} */\nexport default ${cfg};\n`;
  }
}

function cssVars(scales: NamedScale[], o: ExportOptions): string {
  const lines = scales.flatMap((s) => s.steps.map((x) => `  --${s.name}-${x.stop}: ${colorString(x, o.syntax)};`));
  return `${blockHeader(o.sourceUrl)}:root {\n${lines.join("\n")}\n}\n`;
}

function scss(scales: NamedScale[], o: ExportOptions): string {
  const vars = scales.map((s) => s.steps.map((x) => `$${s.name}-${x.stop}: ${colorString(x, o.syntax)};`).join("\n")).join("\n\n");
  const maps = scales
    .map((s) => `$${s.name}: (\n${s.steps.map((x) => `  ${x.stop}: $${s.name}-${x.stop},`).join("\n")}\n);`)
    .join("\n\n");
  return `${lineHeader(o.sourceUrl, "//")}\n${vars}\n\n${maps}\n`;
}

function tree<T>(scales: NamedScale[], leaf: (x: ScaleStep) => T): Record<string, Record<string, T>> {
  return Object.fromEntries(scales.map((s) => [s.name, Object.fromEntries(s.steps.map((x) => [String(x.stop), leaf(x)]))]));
}

function json(scales: NamedScale[], o: ExportOptions): string {
  return JSON.stringify(tree(scales, (x) => colorString(x, o.syntax)), null, 2) + "\n";
}

const round = (n: number, dp: number) => Number(n.toFixed(dp));

function dtcg(scales: NamedScale[]): string {
  const t = tree(scales, (x) => ({
    $type: "color",
    $value: { colorSpace: "oklch", components: [round(x.oklch.l, 4), round(x.oklch.c, 4), round(x.oklch.h, 2)], hex: x.hex },
  }));
  return JSON.stringify({ $description: "Generated by Tintwork (Groundwork Technologies)", ...t }, null, 2) + "\n";
}

function tokensStudio(scales: NamedScale[], o: ExportOptions): string {
  const t = tree(scales, (x) => ({ value: colorString(x, o.syntax === "oklch" || o.syntax === "p3" ? "hex" : o.syntax), type: "color" }));
  return JSON.stringify(t, null, 2) + "\n";
}

function shadcn(scales: NamedScale[], o: ExportOptions): string {
  scales = o.full ?? scales;
  const hasAll = ["brand", "neutral", "success", "warning", "danger", "info"].every((k) =>
    scales.some((s) => (s.kind === "status" ? s.name === k : s.kind === k)),
  );
  if (!hasAll) return "/* shadcn/ui theme needs the brand, neutral and status scales. */\n";
  const fmt = (hex: string) => {
    if (o.syntax === "hex") return hex;
    const ok = hexToOklch(hex);
    return ok ? formatOklch(ok) : hex;
  };
  const block = (sel: string, theme: "light" | "dark") => {
    const t = shadcnTokens(scales, theme);
    const lines = SHADCN_COLOR_TOKENS.map((k) => `  --${k}: ${fmt(t[k]!)};`);
    return `${sel} {\n${theme === "light" ? "  --radius: 0.625rem;\n" : ""}${lines.join("\n")}\n}`;
  };
  const map = SHADCN_COLOR_TOKENS.map((k) => `  --color-${k}: var(--${k});`).join("\n");
  return `${blockHeader(o.sourceUrl)}${block(":root", "light")}\n\n${block(".dark", "dark")}\n\n@theme inline {\n  --radius-sm: calc(var(--radius) - 4px);\n  --radius-md: calc(var(--radius) - 2px);\n  --radius-lg: var(--radius);\n  --radius-xl: calc(var(--radius) + 4px);\n${map}\n}\n`;
}

/** Render scales in the requested format. Deterministic. */
export function exportScales(scales: NamedScale[], o: ExportOptions): string {
  switch (o.format) {
    case "tailwind-v4":
      return tailwindV4(scales, o);
    case "tailwind-v3":
      return tailwindV3(scales, o);
    case "css":
      return cssVars(scales, o);
    case "scss":
      return scss(scales, o);
    case "json":
      return json(scales, o);
    case "dtcg":
      return dtcg(scales);
    case "tokens-studio":
      return tokensStudio(scales, o);
    case "shadcn":
      return shadcn(scales, o);
    case "style-dictionary":
      return styleDictionaryTokens(scales);
    case "css-modern":
      return modernCss(scales, o.full ?? scales, o.sourceUrl);
    case "flutter":
      return flutterDart(scales, o.full ?? scales);
    case "android":
      return androidColorsXml(scales, o.full ?? scales);
    case "compose":
      return composeKotlin(scales, o.full ?? scales);
    case "ios":
      return swiftColors(scales, o.full ?? scales);
  }
}

/** Every format as separate files, ready to zip. */
export function exportFiles(scales: NamedScale[], o: Omit<ExportOptions, "format">): ZipFile[] {
  const full = o.full ?? scales;
  const opts = (format: ExportFormat, extra: Partial<ExportOptions> = {}): ExportOptions => ({ ...o, format, full, ...extra });
  const files: ZipFile[] = [
    { path: "tailwind/theme.css", content: exportScales(scales, opts("tailwind-v4")) },
    { path: "tailwind/tailwind.config.js", content: exportScales(scales, opts("tailwind-v3", { syntax: "hex", v3Module: "esm" })) },
    { path: "css/variables.css", content: exportScales(scales, opts("css")) },
    { path: "css/modern.css", content: exportScales(scales, opts("css-modern")) },
    { path: "css/shadcn-theme.css", content: exportScales(full, opts("shadcn")) },
    { path: "scss/_colors.scss", content: exportScales(scales, opts("scss")) },
    { path: "json/colors.json", content: exportScales(scales, opts("json")) },
    { path: "tokens/dtcg.json", content: exportScales(scales, opts("dtcg")) },
    { path: "tokens/tokens-studio.json", content: exportScales(scales, opts("tokens-studio")) },
    { path: "tokens/style-dictionary/tokens/color.json", content: styleDictionaryTokens(scales) },
    { path: "tokens/style-dictionary/config.json", content: styleDictionaryConfig() },
    { path: "flutter/tintwork_colors.dart", content: flutterDart(scales, full) },
    { path: "android/values/colors.xml", content: androidColorsXml(scales, full) },
    { path: "android/Color.kt", content: composeKotlin(scales, full) },
    { path: "ios/TintworkColors.swift", content: swiftColors(scales, full) },
    ...xcassetsFiles(scales, full),
  ];
  const night = androidNightXml(full);
  if (night) files.push({ path: "android/values-night/colors.xml", content: night });
  const names = scales.map((s) => s.name).join(", ");
  files.push({
    path: "README.md",
    content: `# Tintwork palette export\n\nGenerated by Tintwork (Groundwork Technologies).\n${o.sourceUrl ? `\nOpen and edit this palette: ${o.sourceUrl}\n` : ""}\nScales: ${names}\n\n| Folder | Contents |\n|---|---|\n| tailwind/ | Tailwind v4 \`@theme\` and v3 config |\n| css/ | CSS variables, modern CSS (OKLCH + light-dark), shadcn/ui theme |\n| scss/ | SCSS variables and maps |\n| json/, tokens/ | JSON, W3C design tokens, Tokens Studio, Style Dictionary |\n| flutter/ | Dart: MaterialColor swatches and Material 3 color schemes |\n| android/ | colors.xml (light and night), Jetpack Compose Color.kt |\n| ios/ | SwiftUI colors and an Xcode asset catalog with light and dark |\n`,
  });
  return files;
}

/** All formats in one ZIP archive. */
export function exportZip(scales: NamedScale[], o: Omit<ExportOptions, "format">): Uint8Array {
  return createZip(exportFiles(scales, o));
}
